### PR TITLE
Notes: # Updated 11/25/2024 - plot_V_NV_frames

### PR DESCRIPTION
**Pull request by Rag-hav385**
Taking the config file to read paths to main base form.
Added frame count distplot for violence and non violence.
Updated config to add Visualization Section
Added a Visualization dir.

Creating on fly and update the Visualization dir.

### CODE REVIEW

**Comment by Rag-hav385** [comment]
Hey, guys, a issue in confi data, are you guys keeping your dataset folder inside code dir. in your instance or outside, because while reading, @dhanush-bhargav , you are not tracing back to where code is situated and directly accessing dataset folder.

@Matrix3820 , are you reading the file tracing back to root of root in your dataloader?

**Comment by dhanush-bhargav** [comment]
Dataset folder is inside code directory for me. And you also need to cd
into Code and then run. That's how I'm doing. Sorry for unclear
instructions in readme.
Regards,
Dhanush Bhargav

**Comment by Rag-hav385** [comment]
Can we keep it outside? @dhanush-bhargav

**Comment by dhanush-bhargav** [comment]
So the directory structure is in accordance with what prof has asked in the
project description. So I've kept all code and related files including data
inside the Code directory.
Regards,
Dhanush Bhargav

**Comment by Rag-hav385** [comment]
Okay, will make the structure as asked, as of now, I have kept it outside code, so merging this, will not affect the dataloader and training, this is a one-time run, will update later.

**Pull request merged**
